#ifndef SERVICOENUM_HPP
#define SERVICOENUM_HPP

enum ServicoEnum
{
    // Pessoa
    S1_CRIAR_PESSOA,
    S2_LER_PESSOA,
    S2_LISTAR_PESSOA, // Alias
    S3_ATUALIZAR_PESSOA,
    S4_EXCLUIR_PESSOA,

    // Projeto
    S5_CRIAR_PROJETO,
    S6_LER_PROJETO,
    S6_LISTAR_PROJETO, // Alias
    S7_ATUALIZAR_PROJETO,
    S8_EXCLUIR_PROJETO,
    S19_LISTAR_PROJETOS_ASSOCIADOS_A_PESSOA,

    // Plano de Sprint
    S9_CRIAR_PLANO_SPRINT,
    S10_LER_PLANO_SPRINT,
    S10_LISTAR_PLANO_SPRINT, // Alias
    S11_ATUALIZAR_PLANO_SPRINT,
    S12_EXCLUIR_PLANO_SPRINT,
    S21_LISTAR_PLANOS_DE_SPRINT_ASSOCIADOS_A_PROJETO,

    // História de Usuário
    S13_CRIAR_HISTORIA_USUARIO,
    S14_LER_HISTORIA_USUARIO,
    S14_LISTAR_HISTORIA_USUARIO, // Alias
    S15_ATUALIZAR_HISTORIA_USUARIO,
    S16_EXCLUIR_HISTORIA_USUARIO,
    S17_ESTABELECER_ASSOCIACAO_ENTRE_HU_E_PESSOA,
    S18_REMOVER_ASSOCIACAO_ENTRE_HU_E_PESSOA,
    S20_LISTAR_HU_ASSOCIADAS_A_PROJETO,
    S22_LISTAR_HU_ASSOCIADAS_A_PLANO_SPRINT,
    S23_LISTAR_HU_ASSOCIADAS_A_PESSOA,
    S24_MOVER_HU_DE_PROJETO_PARA_PLANO_SPRINT,
    S25_ALTERAR_ESTADO_DE_HISTORIA_USUARIO,
    S17_ALTERAR_ESTADO,     // Alias
    S18_VINCULAR_PESSOA,    // Alias
    S19_DESVINCULAR_PESSOA, // Alias
    S20_MOVER_PARA_SPRINT,  // Alias
};

#endif // SERVICOENUM_HPP
